import { Product } from "@/types";

export const deals: Product[] = [
  {
    id: 1,
    name: "Wireless Mouse",
    amountInStock: 100,
    currentPrice: 999,
    previousPrice: 1299,
    deliveryPrice: 40,
    deliveryInDays: 2,
    isAmazonChoice: true,
    imageUrl: "https://uniquec.com/wp-content/uploads/235.jpg",
    model3DUrl: null,
    user_id: 0,
    currency: "ZWG",
  },
  {
    id: 2,
    name: "Keyboard",
    amountInStock: 50,
    currentPrice: 1499,
    previousPrice: 1799,
    deliveryPrice: 60,
    deliveryInDays: 3,
    isAmazonChoice: false,
    imageUrl: "https://m.media-amazon.com/images/I/61QxkJGYxeL.jpg",
    model3DUrl: null,
    user_id: 0,
    currency: "ZWG",
  },
  {
    id: 3,
    name: "Wireless Mouse",
    amountInStock: 100,
    currentPrice: 999,
    previousPrice: 1299,
    deliveryPrice: 40,
    deliveryInDays: 2,
    isAmazonChoice: true,
    imageUrl: "https://uniquec.com/wp-content/uploads/235.jpg",
    model3DUrl: null,
    user_id: 0,
    currency: "ZWG",
  },
  {
    id: 4,
    name: "Keyboard",
    amountInStock: 50,
    currentPrice: 1499,
    previousPrice: 1799,
    deliveryPrice: 60,
    deliveryInDays: 3,
    isAmazonChoice: false,
    imageUrl: "https://m.media-amazon.com/images/I/61QxkJGYxeL.jpg",
    model3DUrl: null,
    user_id: 0,
    currency: "ZWG",
  },
];
